### ISSUE TITLE
Ability to chose in what type to compile in  .COM or into .EXE

### ISSUE THREAD

**Issue by RazdolbayOne** [dosasm/masm-tasm#16]
It would be great if you can chose in what type to compile your source file into .COM or into .EXE file
I know you can do what using Emulator button and type command to compile but still it a lot of annoying work. Can you automate it ? Or add parameter to chose whenever compile into .COM or into .EXE?

Also how to run what pretty debugger (RUN ASM DEBUGGER button ) instead of using td debugger when you compile multy source project?

**Comment by xsro** [comment]
I know for `TASM`, we can use `tlink /t` to do this.

so maybe you can paste this code to settings.json 

```jsonc
"masmtasm.dosbox.more": {
        "open": [
            "set path=c:\\masm;c:\\tasm"
        ],
        "tasm": [
            "set path=c:\\tasm",
            "tasm /zi ${filename}.ASM >X:\\ASM.LOG ",
            "@type X:\\ASM.LOG",
            "if exist ${filename}.OBJ tlink /v/3/t ${filename}.obj >X:\\LINK.LOG ",
            "@type X:\\LINK.LOG"
        ],
        "tasm_debug": [
            "if exist ${filename}.com c:\\tasm\\TD ${filename}"
        ],
        "run": [
            "${filename}",
            "@echo (END)Here is the end of the program's output"
        ]
    }
```

**Comment by xsro** [comment]
What does this mean? Is this mean that you want to use another debuger instead of TD.exe? 
> Also how to run what pretty debugger (RUN ASM DEBUGGER button ) instead of using td debugger when you compile multy source project?

**Comment by RazdolbayOne** [comment]
> What does this mean? Is this mean that you want to use another debuger instead of TD.exe?
> 
> > Also how to run what pretty debugger (RUN ASM DEBUGGER button ) instead of using td debugger when you compile multy source project?

I mean you can can run td into two different ways . using "Debug ASM code button "(pic 1)

![pretty_debugger](https://user-images.githubusercontent.com/55252915/107113436-970c0680-6867-11eb-976e-19c3a9bbb8ad.PNG)
 
or using in  emulator command to run debugger in
 ```console 
D:>td yourexe.exe
```
(pic 2) what runs td debugger not in pretty way
then launching debugger using console for example for multiple source files  project

![ugly_one](https://user-images.githubusercontent.com/55252915/107113473-cde21c80-6867-11eb-8129-5ef51284d653.PNG) 

i mean how to launch debugger in pretty way, what commands/keys need to pass as params to run ?

**Comment by xsro** [comment]
I am not very familiar with the TD but I know

When we use the following command, the TD can't get enough information 

```cmd
tasm test.asm
tlink test.obj
td test.exe
```

When we use the following commands, the TD can get enough information. this is also the commands used by the extension. The `/zi` for tasm means **full debug info**;The `/v` for tlink means **full symbolic debug information**

```cmd
tasm /zi test.asm
tlink /v/3 test.obj
td test.exe
```

**Comment by RazdolbayOne** [comment]
> I am not very familiar with multy source assembly project.
> 
> When we use the following command with no param, the TD can't get debug information
> 
> ```batchfile
> tasm test.asm
> tlink test.obj
> td test.exe
> ```
> 
> When we use the following commands with params for debug, the TD can get debug information. Below are also the commands used by the extension. The `/zi` for tasm means **full debug info**;The `/v` for tlink means **full symbolic debug information**
> 
> ```batchfile
> tasm /zi test.asm
> tlink /v/3 test.obj
> td test.exe
> ```
> 
> You can type `tasm /?` and `tlink /?` for more information.

I mean to add option to do so ,for example add here(circle on pic) option if chose then you assemble your source code into .com file 
![picture](https://user-images.githubusercontent.com/55252915/107846203-7d7c3900-6dea-11eb-903b-688a22c9524e.PNG) 

or add option in menu(where is auto detect dosbox and you can chose MSDOS or TASM who will be used to compile program)

**Comment by xsro** [comment]
Hello, @RazdolbayOne 

I added a status bar in the new version and [the configuration for .com file](https://github.com/dosasm/masm-tasm#compile-to-com-files).

If you still need this feature, feel free to reopen this. I am sorry for doing this too late
