### ISSUE TITLE
MASM-TASM怎么更改颜色

### ISSUE THREAD

**Issue by Vincent0706** [dosasm/masm-tasm#19]
我想问一下有没有什么方法可以更改您制作的MASM-TASM的配色方案。我想在其中加一些自己个性化的方案。不知道方不方便透露一下修改的方法。

**Comment by xsro** [comment]
[这](https://www.github.com/xsro/masm-tasm/tree/main/syntaxes%2FREADME.md)是一个简单的说明
vscode的逻辑是先将代码分为不同的token的词，再根据token来高亮

**Comment by Vincent0706** [comment]
请问那个token能在哪里查看？我网上查到好像和Settings Sync插件有关。是通过这个插件把设计好token然后应用在自己电脑的VScode上吗？

**Comment by xsro** [comment]
我不是特别熟悉，推荐看一看官方文档，

- [syntax-highlight-guide](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide)

你说的token和我说的并不是一个东西，那个是用来同步设置的。VSCode代码高亮的过程是

1. [tokenization](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#tokenization)将文本分成不同的部分，每个部分对应不同的token
2. [theming](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#theming)对不同的token渲染颜色，也就是不同的主题

这个插件里面只提供了上面的1。有一说一，我在[assembly.tmLanguage.json](https://github.com/xsro/masm-tasm/blob/main/syntaxes/assembly.tmLanguage.json)里面定义的token匹配规则，可能不是很完善，如果你有更好地方案，欢迎PR，你也可以描述一下你的需求，我看看我能不能淦

**Comment by Vincent0706** [comment]
是这样的，我比较喜欢ASM Code Lens的代码配色，本来想试试能不能自己改成那样的配色。刚才我根据你的介绍试了一下，我把ASM Code Lens的相应文件替换过去已经可以实现配色改变了。但对文字的选中时，相应字段框起来和处于某个段中，这个段的名字会加上白底的效果没有变化。这个是怎么改的？

**Comment by xsro** [comment]
试试在设置中增加这个,就是说使用ASM Code len 的语法高亮，和本插件的运行调试功能，我没有增加触发事件，但是我测试是可以使用的

```
 "files.associations": {
        "*.asm": "asm-collection"
    }
```

**Comment by Vincent0706** [comment]
上面那段代码我试了一下，好像不太行

我指的效果是从这样：
![image](https://user-images.githubusercontent.com/82581024/115147158-42b5ac00-a08c-11eb-8bf8-1c38435d6968.png)

变成这样：
![image](https://user-images.githubusercontent.com/82581024/115147276-d4251e00-a08c-11eb-8d92-a0cb5f56c068.png)

**Comment by xsro** [comment]
我建议直接使用ASMLen's 提供的语法支持功能，两者应该可以同时使用。

```json
"files.associations": {
    "*.ASM": "asm-collection"
  },
```
