### ISSUE TITLE
关于几个bug

### ISSUE THREAD

**Issue by x402** [dosasm/masm-tasm#32]
首先还是非常感谢插件的作者。这款插件也是我上微原课，微原老师极力推荐的，也给我学习微原和汇编提供了很大的帮助。所以我想为该插件留下一些建议。

下面是我在使用新版本插件的时候发现的一些bug：
- [ ] 无法格式化代码，或者进行格式化的时候会把操作数疯狂复制
- [x] (不知道这个算不算bug）DOSbox打开TASM的debug的界面，默认只显示Module/File窗口和Watches窗口，而Regs、Dump窗口默认不显示，需要手动打开（老版本插件进入td界面是默认显示上述4个窗口的）

我用的是老版本vscode，安装插件最高只安装到0.7.0版本的，而0.7.0版本各功能都十分正常。上述bug是我在别的机子用新版vscode（默认安装更新版本的插件）的时候发现的。也不知道是从哪个版本开始有了上述的bug。
另外，我在研究该插件的时候发现使用TD之前插件会将tools\tasm\TDC2.TD复制到workspace里并改名为TDCONFIG.TD，然后在TD的时候才能正常默认显示上述4个窗口（0.7.0版本插件）。我尝试将workspace中的TDCONFIG.TD删除，并手动TD T.EXE，发现debug界面也没有默认显示上述4个窗口（甚至默认显示的是别的窗口）。所以我猜测上述第2点和TDCONFIG.TD这个文件有关？

我还没有学习过插件的制作，很抱歉暂时无法提供代码上的帮助。以后我学习了相关的编程语言后一定会来帮助编写！！

英语不好，就不用英语写了（

**Comment by xsro** [comment]
感谢，我会着手处理这几个问题，并且不能保证修复日期。
由于个人时间有限，所以我在新版中清除了一些我觉得可能不太必要的功能，我希望插件能够做好基于模拟器的DOS系统下简单汇编的小事情，汇编内容太大，我也很久不学汇编了。

**Comment by x402** [comment]
> 感谢，我会着手处理这几个问题，并且不能保证修复日期。 由于个人时间有限，所以我在新版中清除了一些我觉得可能不太必要的功能，我希望插件能够做好基于模拟器的DOS系统下简单汇编的小事情，汇编内容太大，我也很久不学汇编了。
> 
> 顺便可以透露一下你是哪所大学的吗

西电计科大三XD
