### ISSUE TITLE
格式化时文件被还原

### ISSUE THREAD

**Issue by Asttear** [dosasm/masm-tasm#37]
如题。我开启了 VSC 的“Format On Save”功能，然后惊讶地发现代码无法保存了，每次保存都会回到未修改之前的样子。排查后发现好像是插件的格式化功能存在问题，目前只能先关闭“Format On Save”功能手动保存后再格式化代码，希望能够解决。

**Comment by Asttear** [comment]
又测试了一下，只有关闭后再打开文件才能正常格式化代码，否则就会还原，不清楚是否是我的个人配置问题。插件设置已经重置默认，问题依旧。

**Comment by xsro** [comment]
你好，这个插件里面知识提供了一个格式化的简单算法在[AsmDocumentFormattingEdit.ts](https://github.com/dosasm/masm-tasm/blob/main/src/language/AsmDocumentFormattingEdit.ts)文件中。显然目前的格式化算法不够优秀，可能造成代码文件的损失。

我收到了一些关于这个功能的报告，比如：

> 你好，最近在使用vscode该插件时发现格式化后文件修改被恢复，需要重新打开vscode才能完成一次格式化

往往这些问题也与编辑器设置有关，比如打开了保存时自动格式化`editor.formatOnSave`等功能。
我在想，我是否需要移除他，或者在执行这个格式化的时候增加警告信息。

**Comment by Asttear** [comment]
> 

#38 我已经提交了理应修复该问题的 pr，烦请检阅后合并。

**Comment by xsro** [comment]
太赞了，感谢
