### ISSUE TITLE
Cannot read properties of undefined (reading 'fsPath')

### ISSUE THREAD

**Issue by ld1856** [dosasm/masm-tasm#39]
1. `Ctrl` + `Shift` + `p`
2. 'debug asm code' 
3. error:
![image](https://user-images.githubusercontent.com/23313219/168443999-3fa9caa5-e6aa-436b-b764-0ff1d58129b0.png)

log info:
![image](https://user-images.githubusercontent.com/23313219/168444050-49e16bf0-5ffd-4e54-b23d-b96e4f61abd0.png)

[2022-05-15 02:24:50.749] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'fsPath')
	at c:\Users\user\.vscode-insiders\extensions\xsro.masm-tasm-1.1.0\dist\extension.js:1:46204
	at c:\Users\user\.vscode-insiders\extensions\xsro.masm-tasm-1.1.0\dist\extension.js:1:45130

**Comment by xsro** [comment]
Hi, I recommend using this via "right-click" on the editor.
it provides this feature for other extensions, so it is not very smart.

**Comment by ld1856** [comment]
That's a pity. I prefer to use the keyboard. Thank you for your answer.
