### ISSUE TITLE
未能正确区分ASCII的大小写

### ISSUE THREAD

**Issue by wiketool** [dosasm/masm-tasm#44]
![image](https://user-images.githubusercontent.com/64351271/195984570-5b92b600-e86c-4cc2-aa20-a7787997c682.png)
![image](https://user-images.githubusercontent.com/64351271/195984577-247f5c48-96ae-4843-97a3-2a231a1a50ab.png)

**Comment by wiketool** [comment]
可能导致该问题的代码
https://github.com/dosasm/masm-tasm/blob/f4e706cdd702f26c76c7d57ad460feffbd785ad9/src/language/Hover.ts#L67-L71

**Comment by xsro** [comment]
谢谢你，应该修好了
