### ISSUE TITLE
插件中右键无法打开dos环境同时无法运行/调试当前程序

### ISSUE THREAD

**Issue by was3d** [dosasm/masm-tasm#46]
![image-20221115203350717](https://pubpic-1300065410.cos.ap-chengdu.myqcloud.com/typora/image-20221115203350717.png)

如上图无法打开dos环境，报错如上，请问该如何解决？

**Comment by xsro** [comment]
建议修改左下角，不要用msdos，这个程序太不稳定了

**Comment by Real-Rio** [comment]
> 我改成msdos player masm-v5.00后成功运行了
